site_name: Tarea 2 FS0432
nav:
  - Home: index.md
  - Explanation: explanation.md
  - Reference: reference.md
  - Tutorials: tutorials.md

theme:
  name: material
  feature:  
    - navigation.toc

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.] 

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
